import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

import { env } from './env';

/**
 * File storage abstraction.
 *
 * `LocalStorageDriver` is the default and needs no configuration. An S3-style
 * driver is wired to FILE_STORAGE_URL / FILE_STORAGE_KEY so a college can point
 * CampusIQ at object storage later without touching feature code.
 */
export interface StoredObject {
  key: string;
  size: number;
  mimeType: string;
  driver: 'local' | 's3';
  checksum: string;
}

export interface StorageDriver {
  readonly name: 'local' | 's3';
  put(key: string, data: Buffer, mimeType: string): Promise<StoredObject>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

function resolveUploadDir() {
  const configured = env().UPLOAD_DIR;
  const dir = path.isAbsolute(configured) ? configured : path.resolve(process.cwd(), configured);
  return dir;
}

export class LocalStorageDriver implements StorageDriver {
  readonly name = 'local' as const;
  private root = resolveUploadDir();

  private target(key: string) {
    // Prevent path traversal: keys are generated by us, but validate anyway.
    const normalised = path.normalize(key).replace(/^(\.\.[/\\])+/, '');
    if (normalised.includes('\0')) throw new Error('Invalid storage key');
    return path.join(this.root, normalised);
  }

  async put(key: string, data: Buffer, mimeType: string): Promise<StoredObject> {
    const file = this.target(key);
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, data);
    return {
      key,
      size: data.byteLength,
      mimeType,
      driver: 'local',
      checksum: crypto.createHash('sha256').update(data).digest('hex'),
    };
  }

  async get(key: string): Promise<Buffer> {
    return fs.readFile(this.target(key));
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.target(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.access(this.target(key));
      return true;
    } catch {
      return false;
    }
  }
}

/**
 * Minimal S3-compatible driver speaking the REST API of the configured
 * FILE_STORAGE_URL (used for college-provided object storage). Falls back to a
 * clear configuration error rather than silently dropping files.
 */
export class S3StorageDriver implements StorageDriver {
  readonly name = 's3' as const;

  private config() {
    const { FILE_STORAGE_URL, FILE_STORAGE_KEY, FILE_STORAGE_BUCKET } = env();
    if (!FILE_STORAGE_URL || !FILE_STORAGE_KEY) {
      throw new Error('FILE_STORAGE_URL and FILE_STORAGE_KEY must be set for the s3 driver');
    }
    return { url: FILE_STORAGE_URL.replace(/\/$/, ''), key: FILE_STORAGE_KEY, bucket: FILE_STORAGE_BUCKET };
  }

  async put(key: string, data: Buffer, mimeType: string): Promise<StoredObject> {
    const { url, key: token, bucket } = this.config();
    const response = await fetch(`${url}/${bucket ? `${bucket}/` : ''}${key}`, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': mimeType },
      body: new Uint8Array(data),
    });
    if (!response.ok) throw new Error(`Object storage responded ${response.status}`);
    return {
      key,
      size: data.byteLength,
      mimeType,
      driver: 's3',
      checksum: crypto.createHash('sha256').update(data).digest('hex'),
    };
  }

  async get(key: string): Promise<Buffer> {
    const { url, key: token, bucket } = this.config();
    const response = await fetch(`${url}/${bucket ? `${bucket}/` : ''}${key}`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!response.ok) throw new Error(`Object storage responded ${response.status}`);
    return Buffer.from(await response.arrayBuffer());
  }

  async delete(key: string): Promise<void> {
    const { url, key: token, bucket } = this.config();
    await fetch(`${url}/${bucket ? `${bucket}/` : ''}${key}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    }).catch(() => undefined);
  }

  async exists(key: string): Promise<boolean> {
    try {
      await this.get(key);
      return true;
    } catch {
      return false;
    }
  }
}

let driver: StorageDriver | null = null;

export function storage(): StorageDriver {
  if (driver) return driver;
  driver = env().FILE_STORAGE_DRIVER === 's3' ? new S3StorageDriver() : new LocalStorageDriver();
  return driver;
}

export const UPLOAD_LIMITS = {
  resume: { maxMb: 5, mime: ['application/pdf', 'text/plain', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'] },
  job: { maxMb: 5, mime: ['application/pdf', 'text/plain', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'] },
  result: { maxMb: 10, mime: ['application/pdf', 'text/csv', 'application/json'] },
  avatar: { maxMb: 2, mime: ['image/png', 'image/jpeg', 'image/webp'] },
} as const;

export type UploadKind = keyof typeof UPLOAD_LIMITS;

export function validateUpload(kind: UploadKind, mimeType: string, sizeBytes: number) {
  const limit = UPLOAD_LIMITS[kind];
  const maxBytes = Math.min(limit.maxMb, env().MAX_UPLOAD_MB) * 1024 * 1024;
  if (sizeBytes > maxBytes) {
    return { ok: false as const, reason: `File is larger than ${limit.maxMb} MB.` };
  }
  if (!(limit.mime as readonly string[]).includes(mimeType)) {
    return { ok: false as const, reason: `Unsupported file type "${mimeType}". Allowed: ${limit.mime.join(', ')}.` };
  }
  if (sizeBytes === 0) return { ok: false as const, reason: 'The selected file is empty.' };
  return { ok: true as const };
}

/** Build a collision-free storage key for an upload. */
export function storageKey(kind: UploadKind, originalName: string) {
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const rand = crypto.randomBytes(6).toString('hex');
  const ext = path.extname(originalName).toLowerCase().slice(0, 8) || '.bin';
  const safeBase = path
    .basename(originalName, path.extname(originalName))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return `${kind}/${stamp}/${safeBase || 'file'}-${rand}${ext}`;
}
